### ISSUE TITLE
Print Logs for better error detection

### ISSUE THREAD

**Issue by ponceta** [sitn/forLim#7]
Printing a log file could be a great way to debug the plugin use cases (considering different configs/...)

**Comment by monodo** [comment]
Logs are not user friendly, I would better suggest to include some checks and in case of problem, return an explicit message to the user using QGIS integrated message bar instance: self.iface.messageBar() with appropriate level.

_Example:  self.messageBar.pushMessage("Error", "Invalid path", level=QgsMessageBar.CRITICAL)_
